// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHVXJ238CDZSzqM14nMEzj7iYu_VhKxE',
    appId: '1:212786517198:web:ac9ba1409b89b34c7d6c9f',
    messagingSenderId: '212786517198',
    projectId: 'study-app-f4526',
    authDomain: 'study-app-f4526.firebaseapp.com',
    storageBucket: 'study-app-f4526.appspot.com',
    measurementId: 'G-ENBH12DG8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZSrCFQS1ePTfc2NsBfVF_834CSYorvw',
    appId: '1:212786517198:android:adc53c1c41615f2b7d6c9f',
    messagingSenderId: '212786517198',
    projectId: 'study-app-f4526',
    storageBucket: 'study-app-f4526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUL_4C7PWtEgRiWceL9ZD0kIM58TJrYyQ',
    appId: '1:212786517198:ios:3eeb8e4ae7b3ade87d6c9f',
    messagingSenderId: '212786517198',
    projectId: 'study-app-f4526',
    storageBucket: 'study-app-f4526.appspot.com',
    iosClientId: '212786517198-07q0m80tmfkro7jjsa5f8fbnm1tqo9pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUL_4C7PWtEgRiWceL9ZD0kIM58TJrYyQ',
    appId: '1:212786517198:ios:a46eea0ee45eecc37d6c9f',
    messagingSenderId: '212786517198',
    projectId: 'study-app-f4526',
    storageBucket: 'study-app-f4526.appspot.com',
    iosClientId: '212786517198-h3tupvs1hkd3r8rklbvfabs64raqeogn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStorageApp.RunnerTests',
  );
}
